# Generated by Django 3.1.2 on 2023-02-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='capital',
            field=models.BooleanField(default=False),
        ),
    ]
